// <auto-generated />
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.BookI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Title");

                    b.HasKey("id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ConsoleApp1.Borrowing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BTime");

                    b.Property<int?>("Bookid");

                    b.Property<DateTime>("RTime");

                    b.Property<int?>("Userid");

                    b.HasKey("id");

                    b.HasIndex("Bookid");

                    b.HasIndex("Userid");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("ConsoleApp1.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsoleApp1.Borrowing", b =>
                {
                    b.HasOne("ConsoleApp1.BookI", "Book")
                        .WithMany()
                        .HasForeignKey("Bookid");

                    b.HasOne("ConsoleApp1.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid");
                });
#pragma warning restore 612, 618
        }
    }
}
